name: ci

on: [workflow_dispatch]
    
env:
  REGISTRY_NAME: azfunckeda
  CLUSTER_NAME: azfunckeda
  CLUSTER_RESOURCE_GROUP: rg-az-func-keda
  NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.REGISTRY_NAME}}.azurecr.io
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}
        
    - run: |
        docker build . -t ${{env.REGISTRY_NAME}}.azurecr.io/azfunckeda:${{github.sha}}
        docker push ${{env.REGISTRY_NAME}}.azurecr.io/azfunckeda:${{github.sha}}
