name: ci

on:
  push:
    branches: master
    
env:
  REGISTRY_NAME: {registry-name}
  CLUSTER_NAME: {cluster-name}
  CLUSTER_RESOURCE_GROUP: {cluster-resource-group}
  NAMESPACE: {namespace-name}
  APP_NAME: {app-name}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.REGISTRY_NAME}}.azurecr.io
        username: ${{env.AZURE_CLIENT_ID}}
        password: ${{env.AZURE_CLIENT_SECRET}}
        
    - run: |
        docker build . -t ${{env.REGISTRY_NAME}}.azurecr.io/azfunckeda:${{github.sha}}
        docker push ${{env.REGISTRY_NAME}}.azurecr.io/azfunckeda:${{github.sha}}
