name: ci

on: [workflow_dispatch]
    
env:
  REGISTRY_NAME: azfunckeda
  CLUSTER_NAME: azfunckeda
  CLUSTER_RESOURCE_GROUP: rg-az-func-keda
  NAMESPACE: default
  NODE_VERSION: '12.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Nodejs ${{env.NODE_VERSION}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      working-directory: ./src
    
    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ${{env.REGISTRY_NAME}}.azurecr.io
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}

    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: ${{env.REGISTRY_NAME}}.azurecr.io/azfunckeda:${{github.sha}}
        
